// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdP6pvi0FX9hThkby5RCTqex8gq3DSIKQ',
    appId: '1:345912598808:web:e0f45ecfc2845c18093e6d',
    messagingSenderId: '345912598808',
    projectId: 'school-65fb6',
    authDomain: 'school-65fb6.firebaseapp.com',
    storageBucket: 'school-65fb6.appspot.com',
    measurementId: 'G-VLGBEL51NQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJp0xr2VWviOyIHxGZ5OgeZ-GHvPgw9Ok',
    appId: '1:345912598808:android:ac96f615632d3c76093e6d',
    messagingSenderId: '345912598808',
    projectId: 'school-65fb6',
    storageBucket: 'school-65fb6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlVG2USNBuWp-GK-HGWcM_rzc6wYVduGo',
    appId: '1:345912598808:ios:bd8d37ef27e090ca093e6d',
    messagingSenderId: '345912598808',
    projectId: 'school-65fb6',
    storageBucket: 'school-65fb6.appspot.com',
    iosBundleId: 'com.example.school',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlVG2USNBuWp-GK-HGWcM_rzc6wYVduGo',
    appId: '1:345912598808:ios:bd8d37ef27e090ca093e6d',
    messagingSenderId: '345912598808',
    projectId: 'school-65fb6',
    storageBucket: 'school-65fb6.appspot.com',
    iosBundleId: 'com.example.school',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdP6pvi0FX9hThkby5RCTqex8gq3DSIKQ',
    appId: '1:345912598808:web:255448ba97badd3a093e6d',
    messagingSenderId: '345912598808',
    projectId: 'school-65fb6',
    authDomain: 'school-65fb6.firebaseapp.com',
    storageBucket: 'school-65fb6.appspot.com',
    measurementId: 'G-VY3RQVVC4W',
  );
}
